sudo: false
dist: trusty
language: python
cache: pip
python:
  # @see http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/
  # @see https://docs.djangoproject.com/en/dev/releases/1.11/#python-compatibility
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
# - DJANGO="git+https://github.com/django/django.git@master#egg=django"
matrix:
  # @see https://docs.djangoproject.com/en/dev/releases/2.0/#python-compatibility
  exclude:
  - python: "2.7"
    env: DJANGO="Django>=2.0,<2.1"
  - python: "2.7"
    env: DJANGO="Django>=2.1,<2.2"
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
install:
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .[test]
  - pip install coveralls
before_script:
  - createdb -U postgres template_postgis
  - psql -c 'CREATE EXTENSION postgis' -U postgres template_postgis
  - createdb -U postgres travis_ci_test
  - psql -c 'CREATE EXTENSION postgis' -U postgres travis_ci_test
  - django-admin.py migrate --settings settings --noinput
script:
  - coverage run --source=boundaries runtests.py
after_success:
  coveralls
