sudo: false
language: python
cache: pip
python:
  # @see http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
# - DJANGO="git+https://github.com/django/django.git@master#egg=django"
matrix:
  exclude:
    # @see https://docs.djangoproject.com/en/dev/releases/1.7/#python-compatibility
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"
install:
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .[test]
  - pip install coveralls
before_script:
  - createdb -U postgres template_postgis
  - psql -c 'CREATE EXTENSION postgis' -U postgres template_postgis
  - createdb -U postgres travis_ci_test
  - psql -c 'CREATE EXTENSION postgis' -U postgres travis_ci_test
  - django-admin.py syncdb --settings settings --noinput
script:
  - coverage run --source=boundaries runtests.py
after_success:
  coveralls
