sudo: false
language: python
cache: pip
python:
  # https://devguide.python.org/#branchstatus
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  # https://docs.djangoproject.com/en/dev/releases/
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<2.3"
  # - DJANGO="Django>=3.0,<3.1"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
install:
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .[test]
  - pip install coveralls
before_script:
  - createdb -U postgres template_postgis
  - psql -c 'CREATE EXTENSION postgis' -U postgres template_postgis
  - createdb -U postgres travis_ci_test
  - psql -c 'CREATE EXTENSION postgis' -U postgres travis_ci_test
  - django-admin.py migrate --settings settings --noinput
script:
  - coverage run --source=boundaries runtests.py
after_success:
  coveralls
