language: python
python:
  # @see http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"
# - DJANGO="git+https://github.com/django/django.git@master#egg=django"
install:
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .[test]
before_script:
  - createdb -U postgres template_postgis
  - psql -c 'CREATE EXTENSION postgis' -U postgres template_postgis
  - createdb -U postgres travis_ci_test
  - psql -c 'CREATE EXTENSION postgis' -U postgres travis_ci_test
  - django-admin.py syncdb --settings settings --noinput
script:
  - python runtests.py
